config/routes.rb
Rails.application.routes.draw do

  resources :documents

  root 'documents#index'

end

app/models/document.rb
class Document

  include Mongoid::Document
  include Elasticsearch::Model

  field :file_title
  field :author
  field :categories, type: Array
  field :file_location
  field :meta_data, type: Hash
  attr_accessible :meta_data, :file_title, :author, :file_location, :category if respond_to? :attr_accessible

  def as_indexed_json(options={})
    as_json(except: [:id, :_id])
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.page(params[:page])
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:file_title, :author, :file_url, :category)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_for(@document) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :file_title %><br>
    <%= f.text_field :file_title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :file_url %><br>
    <%= f.text_field :file_url %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing Document</h1>

<%= render 'form' %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.haml
%p#notice= notice

.fixed
  %nav.top-bar{data: {topbar: true}, role: "navigation"}
    %ul.title-area
      %h3
        %a#title-text{href: root_path} AHU E-Library
    %section.top-bar-section
      %ul.right
        %li.has-form
          .row.collapse
            .large-8.small-9.columns
              %input{type: "text", placeholder: "..."}
            .large-4.small-3.columns
              %a.alert.button.expand{href:"#"}Search

%br
%br


%table{summary: "Resources for Researchers and Students of Knowledge",
       style: "margin-left:auto;margin-right:auto"}
  %thead
    %th Title
    %th Author
    %th Info
  %tbody
    - @documents.each do |document|
      %tr
        %td= link_to document.file_title, document.file_location
        %td= document.author
        %td= link_to 'More Info', document




%br/
= paginate @documents
= link_to 'New Document', new_document_path

app/views/documents/new.html.erb
<h1>New Document</h1>

<%= render 'form' %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>File title:</strong>
  <%= @document.file_title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @document.author %>
</p>

<p>
  <strong>Categories:</strong>
  <%= @document.categories %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>

app/views/layouts/application.html.haml
!!! 5
%html{ :lang => "en"}
  %head
    %meta{ :charset => "utf-8" }

    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

    %title= content_for?(:title) ? yield(:title) : "Untitled"

    = stylesheet_link_tag "application", 'data-turbolinks-track' => true
    = javascript_include_tag "vendor/modernizr"
    = javascript_include_tag "application", 'data-turbolinks-track' => true
    = csrf_meta_tag

  %body

    = yield

app/views/layouts/documents.html.haml
!!! 5
%html{ :lang => "en"}
  %head
    %meta{ :charset => "utf-8" }

    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

    %title= content_for?(:title) ? yield(:title) : "Untitled"

    = stylesheet_link_tag "application"
    = javascript_include_tag "vendor/modernizr"
    = javascript_include_tag "application", 'data-turbolinks-track' => true
    = csrf_meta_tag

  %body

    = yield